version: '3'

networks:
  app-tier:
    driver: bridge
services:
  backend:
    image: fidbackhub-api
    container_name: fidbackhub-api
    depends_on:
      - db
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: true
    ports:
      - "1337:1337"
    networks:
      - app-tier
    volumes:
      - ./app:/srv/app
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    ports:
      - '3306:3306'
    networks:
      - app-tier
    volumes:
      - ./db:/var/lib/mysql